[WIP] Passport local strategy
Jordan141/shanemock pull request #3
Opened 2020-11-24 21:19 UTC by Jordan141

Implements passport local strategy and other things as per #2 

resolves #2

2020-11-28 10:57 UTC, michaelKurowski requested changes

2020-11-28 10:57 UTC, michaelKurowski commented on account/login.js
> +        dbConnectionProvider.getDbConnection().model('localUsers').findOne({username}, "password salt", function (err, user) {
AFAIK Mongoose lets you to return a promise instead of putting a callback. Try to avoid callbacks whenever an API provides you promises.

2020-11-28 10:57 UTC, michaelKurowski commented on account/login.js
> +            if (err) reject(false)
return from the function here to break it.

2020-11-28 10:57 UTC, michaelKurowski commented on account/login.js
> +            if (Utilities.createSaltedHash(user.salt, password) == user.password) resolve(true)
Also return from the function here

2020-11-28 10:57 UTC, michaelKurowski commented on account/verification.js
> +    if (username === undefined || username === null) return false
Just `if (username)` should be enough, right? It will also check whether username is not an empty string as a bonus.

2020-11-28 10:57 UTC, michaelKurowski commented on account/verification.js
> +    const alphanumeric = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwqyz0123456789"
This seem like a good util function. I'd suggest to extract it into a separate function like `validateCharset(charset, text)`, that would check whether the `text` has only characters from the charset, you could then also validate email.

2020-11-28 10:57 UTC, michaelKurowski commented on account/verification.js
> +    for (let i = 0; i < username.length; i++) {
Try to avoid loops. Use `[...username].some` instead. It's considered to be a bad practice usually in JS to use loops when you have a more readable alternative.

2020-11-28 10:57 UTC, michaelKurowski commented on account/verification.js
> +    // if (email.indexOf('@') > email.indexOf('.')) return false
Commented code

2020-11-28 10:57 UTC, michaelKurowski commented on account/verification.js
> +    if (email === undefined || email === null) return false
`if (email)`

2020-11-28 10:57 UTC, michaelKurowski commented on account/verification.js
> +    if (password === undefined || password === null) return false
`if (password)`

2020-11-28 10:57 UTC, michaelKurowski commented on passport/strategies/localLogin.js
> +        Users.findOne({username : username}, function (err, user) {
Use API option based on Promises, instead of callbacks.

2020-11-28 10:57 UTC, michaelKurowski commented on routes/oauth.js
> +router.get('/google', passport.authenticate('google', {scope: ['profile email']}))
Avoid magic strings

2020-11-28 10:57 UTC, michaelKurowski commented on routes/local.js
> +router.post('/login', passport.authenticate('local'), (req, res) => {
For route, I'd say it's fine, but for authenticate get rid of magic string.

2020-11-28 15:19 UTC, michaelKurowski requested changes

2020-11-28 15:19 UTC, michaelKurowski commented on account/login.js
> +        dbConnectionProvider.getDbConnection().model('localUsers').findOne({username}, "password salt").then((err, user) => {
Don't nest promises callback. Instead form `then` chains.

2020-11-28 15:19 UTC, michaelKurowski commented on utils.js
> +		[...text].forEach((value) => {
As I said, use `.some`. `.forEach here is unecessary`.

2020-12-01 16:08 UTC, michaelKurowski requested changes

2020-12-01 16:08 UTC, michaelKurowski commented on account/login.js
> +        .then((user) => {
Intendation

2020-12-01 16:08 UTC, michaelKurowski commented on account/login.js
> +        localUser.findOne({username}, 'password salt')
You won't need `return new Promise((resolve, reject) => {`, if you'll do 
`localUser.findOne({username}, 'password salt').exec()`
in such case the beginning of the first line of `verifyPassword` would see like that:
`return localUser.findOne({username}, 'password salt').exec()`

You'd lose resolve/reject but then you can just throw/return value instead

2020-12-01 16:08 UTC, michaelKurowski commented on passport/strategies/localLogin.js
> +        .then((result) => {
You nested thens again

2020-12-01 16:08 UTC, michaelKurowski commented on passport/strategies/localLogin.js
> +    localUser.findOne({username : username})
Use it with `exec`, also the cb of `LocalStrategy` doesn't return anything, is it a valid behaviour?

2020-12-01 16:08 UTC, michaelKurowski commented on routes/local.js
> +    if (!verifyUsername(req.body.username)) return res.sendStatus(400)
Not obligatory but `const {username, email, password} = req.body` would probably cleanup the code a bit

2020-12-01 16:08 UTC, michaelKurowski commented on routes/local.js
> +    const salt = Utilities.generateSalt(80)
Shouldn't `80` be configurable?

2020-12-01 16:08 UTC, michaelKurowski commented on routes/local.js
> +    const password = Utilities.createSaltedHash(salt, req.body.password)
If you'd do `const {username, email, password} = req.body`, then this one likely would be called `hashedPassword` :)

2020-12-01 16:08 UTC, michaelKurowski commented on utils.js
> +		if([...text].some((element) => !charset.includes(element))) return false
Don't write such long if conditions, instead save the result of `[...text].some((element) => !charset.includes(element))` to a constant

2020-12-03 14:07 UTC, michaelKurowski requested changes

2020-12-03 14:07 UTC, michaelKurowski commented on passport/strategies/localLogin.js
> +    localUser.findOne({username})
is it working without `exec`? @Jordan141 could u test whether it works as expected?

2020-12-03 14:07 UTC, michaelKurowski commented on routes/local.js
> +    if (!verifyPassword(password)) return res.sendStatus(400)
`if(!verifyEmail(email) || !verifyPassword(password) || !verifyUsername(username)) return res.sendStatus(400)`

2020-12-03 14:07 UTC, michaelKurowski commented on utils.js
> +		const undesirableChars = [...text].some((element) => !charset.includes(element))
`hasUndesirableChars`, indicate the boolean type by naming them as if they'd be answering a question.

2020-12-03 14:07 UTC, michaelKurowski commented on utils.js
> +		if(undesirableChars) return false
Basically `return !undesirableChars`, but then it would be a bit hard to read as !**un**desirable is kind of a double negation in semantics, so it would probably be better to turn 
`const undesirableChars = [...text].some((element) => !charset.includes(element))`
into
`const hasOnlyValidChars = [...text].every((element) => charset.includes(element))`
and then
`return hasOnlyValidChars`

2020-12-03 15:32 UTC, michaelKurowski commented on routes/local.js
> +    if (!verifyPassword(password)) return res.sendStatus(400)
Eventually in two lines
```
if(!verifyEmail(email) || !verifyPassword(password) || !verifyUsername(username))
     return res.sendStatus(400)
```

2020-12-04 14:27 UTC, michaelKurowski approved these changes
If it's working then I approve it

2020-12-04 14:37 UTC, Jordan141 reviewed
Some small code smell changes and a hanging TODO remain

2020-12-04 14:37 UTC, Jordan141 commented on account/verification.js
> +    console.log(Utilities.verifyCharset(Utilities.alphanumericCharset, username))
remove console.log

2020-12-04 14:37 UTC, Jordan141 commented on passport/strategies/localLogin.js
> +    .catch(err => { return done(err) })
This will show server error details to the user, change it to something else

2020-12-04 14:37 UTC, Jordan141 commented on account/login.js
> +
remove unused imports

2020-12-04 14:37 UTC, Jordan141 commented on db/schema/localUser.js
> +
What's up with this TODO?

2020-12-04 14:37 UTC, Jordan141 commented on passport/strategies/localLogin.js
> +const passport = require('passport')
remove unused imports

2020-12-04 14:37 UTC, Jordan141 commented on routes/local.js
> +    localUser.create(newUser, (err, newUser) => {
second newUser is never used, you should be able to remove it

2020-12-04 14:43 UTC, Jordan141 commented
What happens if I signup with a username or email that already exists, am I notified that it's a duplicate?

2020-12-04 16:47 UTC, jpitucha commented
> What happens if I signup with a username or email that already exists, am I notified that it's a duplicate?

You get 400/401

2020-12-04 18:03 UTC, merged